### ISSUE TITLE
Error launching instance, possible mismatch of Security Group IDs and Names (On terraform-aws-ansible-lab)

### ISSUE THREAD

**Issue by Maheshrjl** [ginigangadharan/terraform-iac-usecases#1]
Error code :
```
AWS Error: InvalidParameterValue: Value () for parameter groupId is invalid. The value cannot be empty
status code: 400, request id: ##################
with aws_instance.ansible-nodes[0],
on ansible-nodes.tf line 2, in resource "aws_instance" "ansible-nodes":
2: resource "aws_instance" "ansible-nodes" {
```

Version Info:
```
Terraform v1.0.1
on windows_amd64
+ provider registry.terraform.io/hashicorp/aws v3.48.0
```

**Comment by ginigangadharan** [comment]
Hi @Maheshrjl ,
Could you please share full log if possible ?

I can check it before I try something here.

**Comment by Maheshrjl** [comment]
Hi @ginigangadharan,

Please find the Full error code [here](https://gist.github.com/Maheshrjl/c5f2dc373b2065f27d7b9aab88cd99af)

Perhaps conflict is arising because of default security groups already existing on my vpc. But I'm unable to troubleshoot further as default VPC & security groups in my AWS account have not been modified. I tried troubleshooting in different region as well but same error persists.

Thanks for helping me troubleshoot this issue.

**Comment by ginigangadharan** [comment]
Hi @Maheshrjl,
That was my bad. I have changed some security group name and missed to update via variable. 
you may checkout the latest code and test it.

Thank you.

**Comment by Maheshrjl** [comment]
This fixes the issue. I'm able to access ansible labs easily now. 
Thank you
